feat(BookRepository): implements createBook method and add Exception
wrideveloper/perpustakaan pull request #1
Opened 2023-10-05 07:46 UTC by FlaBBB

2023-10-07 14:53 UTC, elianiva requested changes

2023-10-07 14:53 UTC, elianiva commented on src/main/java/repository/BookRepository.java
> +    public Book createBook(Book book) throws BookAlreadyExistsExcepetion {
emang bener ini signaturenya? ga sesuai sama yg ada di interface

2023-10-07 15:06 UTC, FlaBBB commented on src/main/java/repository/BookRepository.java
> +    public Book createBook(Book book) throws BookAlreadyExistsExcepetion {
Oh iya mas, belum saya ganti ternyata

2023-10-08 01:40 UTC, FlaBBB commented
gimana mas sekarang?

2023-10-08 08:33 UTC, elianiva approved these changes
LGTM

2023-10-08 08:35 UTC, merged