feat : add getbooks feature
wrideveloper/perpustakaan pull request #3
Opened 2023-10-05 13:06 UTC by Noklent-Fardian

I don't know how it works.

2023-10-07 14:57 UTC, elianiva requested changes

2023-10-07 14:57 UTC, elianiva commented on src/main/java/repository/BookRepository.java
> +    }
classnya ngga boleh ngethrow `ParseException`, buat dummy data cari cara lain biar ngga perlu pake `SimpleDateFormat`

2023-10-08 15:33 UTC, Noklent-Fardian commented on src/main/java/repository/BookRepository.java
> +    }
Rogers!

2023-10-08 17:39 UTC, elianiva approved these changes
LGTM

2023-10-08 17:39 UTC, merged

2023-10-08 17:40 UTC, Noklent-Fardian commented
Aye aye ,sir. o7